# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: detect-private-key
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: clang-format
      args: [-style=file, -i]
    #- id: clang-tidy
    #- id: include-what-you-use
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
    - id: git-check
    - id: shellcheck
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
    - id: remove-crlf
    - id: remove-tabs
#- repo: https://github.com/avilaton/add-msg-issue-prefix-hook
#  rev: v0.0.5  # Use the ref you want to point at
#  stages: [prepare-commit-msg]
#  hooks:
#    - id: add-msg-issue-prefix
